repos:
  - repo: local
    hooks:
      - id: compile-check
        name: Check that the module was was compiled
        entry: bash -c 'npm run compile && git diff --no-patch --exit-code'
        language: system
        verbose: true
