name: "Scale an ECS service"
description: "Scale an ECS service by setting the desired task count"
inputs:
  runner-hash:
    description: >-
      If you are using the self-hosted github runner module, the module will generate a hash for naming the service and cluster. You can set that unique hash here instead of setting the 'service' and 'cluster' variables.
    required: false
    default: ""
  cluster:
    description: "The name of the ECS cluster the service belongs to."
    required: false
    default: ""
  service:
    description: "The name of the ECS service."
    required: false
    default: ""
  desired-count:
    description: "The number of ECS tasks you wish to deploy for the specified service."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
